# Generated by Django 5.1.4 on 2025-01-04 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nConcurso', models.IntegerField(verbose_name='Número do Concurso')),
                ('data_concurso', models.DateField(verbose_name='Data do Concurso')),
                ('bola1', models.IntegerField(verbose_name='Bola 1')),
                ('bola2', models.IntegerField(verbose_name='Bola 2')),
                ('bola3', models.IntegerField(verbose_name='Bola 3')),
                ('bola4', models.IntegerField(verbose_name='Bola 4')),
                ('bola5', models.IntegerField(verbose_name='Bola 5')),
                ('bola6', models.IntegerField(verbose_name='Bola 6')),
                ('bola7', models.IntegerField(verbose_name='Bola 7')),
                ('bola8', models.IntegerField(verbose_name='Bola 8')),
                ('bola9', models.IntegerField(verbose_name='Bola 9')),
                ('bola10', models.IntegerField(verbose_name='Bola 10')),
                ('bola11', models.IntegerField(verbose_name='Bola 11')),
                ('bola12', models.IntegerField(verbose_name='Bola 12')),
                ('bola13', models.IntegerField(verbose_name='Bola 13')),
                ('bola14', models.IntegerField(verbose_name='Bola 14')),
                ('bola15', models.IntegerField(verbose_name='Bola 15')),
                ('ganhadores_15', models.IntegerField(blank=True, null=True, verbose_name='Ganhadores 15 Acertos')),
                ('rateio_15', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rateio 15 Acertos')),
                ('ganhadores_14', models.IntegerField(blank=True, null=True, verbose_name='Ganhadores 14 Acertos')),
                ('rateio_14', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rateio 14 Acertos')),
                ('ganhadores_13', models.IntegerField(blank=True, null=True, verbose_name='Ganhadores 13 Acertos')),
                ('rateio_13', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rateio 13 Acertos')),
                ('ganhadores_12', models.IntegerField(blank=True, null=True, verbose_name='Ganhadores 12 Acertos')),
                ('rateio_12', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rateio 12 Acertos')),
                ('ganhadores_11', models.IntegerField(blank=True, null=True, verbose_name='Ganhadores 11 Acertos')),
                ('rateio_11', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rateio 11 Acertos')),
                ('acumulado_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Acumulado Total')),
                ('estimativa_premio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Estimativa de Prêmio')),
                ('acumulado_especial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Acumulado Sorteio Especial')),
                ('cidade_uf', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade/UF')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('nJogo', models.AutoField(primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('nomeJogo', models.CharField(max_length=255)),
                ('bola1', models.IntegerField()),
                ('bola2', models.IntegerField()),
                ('bola3', models.IntegerField()),
                ('bola4', models.IntegerField()),
                ('bola5', models.IntegerField()),
                ('bola6', models.IntegerField()),
                ('bola7', models.IntegerField()),
                ('bola8', models.IntegerField()),
                ('bola9', models.IntegerField()),
                ('bola10', models.IntegerField()),
                ('bola11', models.IntegerField()),
                ('bola12', models.IntegerField()),
                ('bola13', models.IntegerField()),
                ('bola14', models.IntegerField()),
                ('bola15', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
